server:
  port: 8001

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-service
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka